### ISSUE TITLE
Tidal Modulator 1 crashes on Rack v2

### ISSUE THREAD

**Issue by Petervos2018** [VCVRack/AudibleInstruments#130]
[TidalCrash.zip](https://github.com/user-attachments/files/16180710/TidalCrash.zip)

![afbeelding](https://github.com/VCVRack/AudibleInstruments/assets/46076474/24745d11-9e06-4d6d-9933-b72ae9f995d8)

Remove the clock from Tidal, then reconnect the clock and hit the frequency range button a few times. Instant crash. (No log.txt error)

Greetings Peter.

See also #80

**Comment by SteveRussell33** [comment]
GDB log (Windows)
```
Thread 33 received signal SIGFPE, Arithmetic exception.
[Switching to Thread 21184.0x2c54]
0x00007ffb4bef8113 in tides::Generator::ProcessAudioRate (this=this@entry=0x6f597e0, in=0x6f598a4 '\004' <repeats 28 times>, "\017", out=0x6f597f2,
    out@entry=0x6f597e0, size=15, size@entry=16) at eurorack/tides/generator.cc:414
414             uint32_t t = (phase - mid_point) / (phase_increment >> 16);
(gdb) bt
#0  0x00007ffb4bef8113 in tides::Generator::ProcessAudioRate (this=this@entry=0x6f597e0, in=0x6f598a4 '\004' <repeats 28 times>, "\017", out=0x6f597f2,
    out@entry=0x6f597e0, size=15, size@entry=16) at eurorack/tides/generator.cc:414
#1  0x00007ffb4bf63739 in tides::Generator::Process (wavetableHack=<optimized out>, this=0x6f597e0) at ./eurorack/tides/generator.h:161
#2  Tides::process (this=0x6f59690, args=...) at src/Tides.cpp:128
#3  0x00007ffb50fa6684 in rack::engine::Module::doProcess (this=0x6f59690, args=...) at src/engine/Module.cpp:345
#4  0x00007ffb50fa2201 in rack::engine::Engine_stepWorker (that=0x0, threadId=0) at src/engine/Engine.cpp:316
#5  rack::engine::Engine_stepFrame (that=<optimized out>) at src/engine/Engine.cpp:350
#6  rack::engine::Engine::stepBlock (this=<optimized out>, this@entry=0x6ae7730, frames=<optimized out>, frames@entry=800) at src/engine/Engine.cpp:509
#7  0x00007ffb50fa302b in rack::engine::Engine_fallbackRun (that=0x6ae7730) at src/engine/Engine.cpp:1332
#8  0x00007ffb6ac1bf9f in ?? () from C:\Program Files\VCV\Rack2 Pro\libstdc++-6.dll
#9  0x00007ffb881f4d0b in ?? () from C:\Program Files\VCV\Rack2 Pro\libwinpthread-1.dll
#10 0x00007ffb9d86af5a in msvcrt!_beginthreadex () from C:\WINDOWS\System32\msvcrt.dll
#11 0x00007ffb9d86b02c in msvcrt!_endthreadex () from C:\WINDOWS\System32\msvcrt.dll
#12 0x00007ffb9d587374 in KERNEL32!BaseThreadInitThunk () from C:\WINDOWS\System32\kernel32.dll
#13 0x00007ffb9ed7cc91 in ntdll!RtlUserThreadStart () from C:\WINDOWS\SYSTEM32\ntdll.dll
#14 0x0000000000000000 in ?? ()
```
